# -*- coding: utf-8 -*-
"""Location Finder

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZoK8e_zWnNxWynP0736bU4XRflTuZ7BT
"""

import requests

# Your API Keys
NUMVERIFY_API_KEY = "19c5e5d7786a38c2e0649c6021384ac1"
OPENCAGE_API_KEY = "f26zbdae68d4489b9fad06b9287czp0f"

def get_phone_details(phone_number):
    """Fetch phone details from NumVerify API"""
    url = f"http://apilayer.net/api/validate?access_key={NUMVERIFY_API_KEY}&number={phone_number}"
    response = requests.get(url)
    return response.json()

def get_coordinates(location):
    """Convert location text into coordinates using OpenCage API"""
    url = f"https://api.opencagedata.com/geocode/v1/json?q={location}&key={OPENCAGE_API_KEY}"
    response = requests.get(url).json()

    if response['results']:
        lat = response['results'][0]['geometry']['lat']
        lng = response['results'][0]['geometry']['lng']
        return lat, lng
    return None, None

if __name__ == "__main__":
    # Ask user to enter phone number
    phone_number = input("📱 Enter phone number (with country code, e.g. +919999951151): ")

    # Get phone details
    details = get_phone_details(phone_number)

    if details.get("valid"):
        print("\n✅ Phone Number Details:")
        print(details)

        # Extract location info
        location = details.get("location", "")
        if location:
            lat, lng = get_coordinates(location)
            if lat and lng:
                print(f"📍 Coordinates of {location}: {lat}, {lng}")
            else:
                print("❌ Could not fetch exact coordinates.")
        else:
            print("❌ No location found for this number.")
    else:
        print("❌ Invalid phone number")
